version: '3.4'

services:
  eventstore.db:
    image: eventstore/eventstore
    command: --dev --enable-external-tcp --ext-ip=0.0.0.0 --int-ip=0.0.0.0 --disable-external-tcp-tls
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_INT_TCP_PORT=1112
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_INT_HTTP_PORT=2112
      - EVENTSTORE_EXT_HTTP_PORT=2113
    ports:
      - "1112:1112"
      - "1113:1113"
      - "2112:2112"
      - "2113:2113"
  postgres:
    image: postgres:13.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docman
      - POSTGRES_PASSWORD=DocmanDocman
      - POSTGRES_DB=Docman